# azure-pipelines.yml
trigger:
  - main

pool:
  name: 'Azure Pipelines'


steps:
  - script: |
      TF_VERSION="1.5.7"
      wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      unzip terraform_${TF_VERSION}_linux_amd64.zip
      sudo mv terraform /usr/local/bin/
      terraform --version
      displayName: 'Terraform Install'


  - script: |
      terraform init
      terraform validate
      terraform plan
    displayName: 'Run Terraform Locally'
